### ISSUE TITLE
webpage - available statistics in statistic tab

### ISSUE THREAD

**Issue by Geralds999** [woifal/clLib#149]
Default filter - "last cimb" bei öffnen der statistik seite.
Available statistik filters (time based):
"Last month"
"Last quarter"
"Last year"
"All"

Addiditional statistics (best of):
"Best 10 routes last year"
"Best 10 routes all time"
"Best 10 routes last 3 months"

Additional statistics (progress):
"High score progress last year"
"High score progress 3 months"
"High score progress 1 month"

**Comment by woifal** [comment]
closing defect - raising separate one for:

Addiditional statistics (best of):
"Best 10 routes last year"
"Best 10 routes all time"
"Best 10 routes last 3 months"
