### ISSUE TITLE
web - Google login not working

### ISSUE THREAD

**Issue by Geralds999** [woifal/clLib#173]
same behaviour as for facebook login - not possible.

**Comment by woifal** [comment]
google login funkt bei mir - facebook allerdings wirklcih nicht :/

2015-01-31 16:49 GMT+01:00 Geralds999 <notifications@github.com>:

> same behaviour as for facebook login - not possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woifal/clLib/issues/173>.
>



-- 

   Wolfgang Dietersdorfer
   tel.: 0660/6573712
   email: wolfgang.dietersdorfer@gmail.com

**Comment by Geralds999** [comment]
stimmt, google hat dann funktioniert.

Am 31.01.2015 um 19:52 schrieb woifal <notifications@github.com>:
