### ISSUE TITLE
app - final adaptions for go live

### ISSUE THREAD

**Issue by Geralds999** [woifal/clLib#236]
MOBILE:
Remove "Connect to server" on logon (red banner above) 
  => done

Colour selector: remove "More" when no more colours are available

"More details" button - empty description (Replace with Style)
  => done by renaming to "more.."

Remove debug info when saving route "index.html ...."
=> done

Statistics current status?
- remove debug info
  => done

- Left select button - add border space to left margin
  => done

- If possible add new smaller button for subsection
  => done

Today statistic should be shown first
 => is shown first already => done

Top 10 (last 365 days)
- inflate all 10 routes when selected
=> done
- Date, Grade, Style, points, colour
=> ???????

High Score (by day)
- x-axis: months only
 => done
- y-axis: 2000 points increments
 => done by showing only min/max value of currently selected users

New Statistic "Ranking"
- Overall Ranking (rank, name, points based on last 365 days)
- Buddy Rank

- default to simple tracking mode 
- remove preference option swithc simple tracking yes/no
 => really?!?!?!?????????????

Preferences:
- Add left margin for Terms and Condition text
  => done

- Add margin in feedback form
  => done

- Feedback form: "send feedback" move to bottom
  => done

**Comment by woifal** [comment]
opening separate issue for "ranking" statistics
