### ISSUE TITLE
www.kurt-climbing.com Finals

### ISSUE THREAD

**Issue by Geralds999** [woifal/clLib#237]
1. www.kurtclimbing.com is not available
     
2. when creating new route, column "Ticktype" is not available
      => fixed
3. "Comments" column is right aligned, should be left-aligned
     => fixed
4. Statistics "High score by day" only shows stats for last 3 months - should be 1 year
     => only showing 3 months deliberately. 1 year shows no progression (which is mostly very low) 
            curve would be too flat.

5. Statistics "Top 10...": no details shown - no date, no route info. Point info overlaps with route number. Better would be x-axis: route no. y-axis: points. Show date of route done

6. New route "+" add info "new route" when mouse-over as info possible?
     => fixed

**Comment by woifal** [comment]
opening 2 separate bugs for remaining isuses
